name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /var/www/${{ secrets.SSH_HOST }}
          php artisan down --message="Deploying new changes. Site will be back shortly." --retry=15
          git pull
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan optimize:clear
          php artisan up
          exit
