name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    
    steps:
    - name: Establish connection
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        
    - name: Deploying updates to site
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && php artisan down --retry=15 && git pull && composer install --no-dev --optimize-autoloader && php artisan migrate --force && php artisan optimize:clear && php artisan up && exit"
      
    - name: cleanup
      run: rm -rf ~/.ssh
